package me.perfectly.megawalls;

import java.util.HashMap;

import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.Potion;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.potion.PotionType;

public class KitAPI {
	
	public static ItemStack zombie;
	public static ItemMeta zombiemeta;
	public static ItemStack zombiePot;
	public static ItemMeta zombiePotmeta;
	public static ItemStack spider;
	public static ItemMeta spidermeta;
	public static ItemStack spiderPot;
	public static ItemMeta spiderPotmeta;
	public static ItemStack dread;
	public static ItemMeta dreadmeta;
	public static ItemStack dreadPot;
	public static ItemMeta dreadPotmeta;
	public static ItemStack endyPot;
	public static ItemMeta endyPotmeta;
	public static ItemStack hbPot;
	public static ItemMeta hbPotmeta;
	public static ItemStack skelyPot;
	public static ItemMeta skelyPotmeta;
	public static ItemStack creeperPot;
	public static ItemMeta creeperPotmeta;
	public static ItemStack blazePot;
	public static ItemMeta blazePotmeta;
	public static ItemStack pigPot;
	public static ItemMeta pigPotmeta;
	
	public static HashMap<String, String> Kit = new HashMap<>();
	
	public static void setKit(Player p, String kit){
		Kit.put(p.getName(), kit);
	}
	
	public static String getKit(Player p){
		if(Kit.containsKey(p.getName())){
			return Kit.get(p.getName());
		}else{
			return "Nenhum";
		}
	}
	
	public static void RemoveKit(Player p){
		Kit.remove(p.getName());
		
	}
	@SuppressWarnings("deprecation")
	public static void Zombie(Player p) {
		p.getInventory().clear();
		setKit(p, "Zombie");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		p.getInventory().setHelmet(new ItemStack(Material.IRON_HELMET));
		ItemStack ZombieChest = new ItemStack(Material.DIAMOND_CHESTPLATE);
		ZombieChest.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
		ItemMeta ZombieChestMeta = ZombieChest.getItemMeta();
		ZombieChestMeta.setDisplayName("§b Zombie Chestplate");
		ZombieChest.setItemMeta(ZombieChestMeta);
		p.getInventory().setChestplate(ZombieChest);
		p.getActivePotionEffects().clear();
		ItemStack ZombieSword = new ItemStack(Material.IRON_SWORD);
		ZombieSword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta ZombieSwordMeta = ZombieSword.getItemMeta();
		ZombieSwordMeta.setDisplayName("§bZombie Sword");
		ZombieSword.setItemMeta(ZombieSwordMeta);
		p.getInventory().setItem(0, ZombieSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		zombiePot = new ItemStack(Material.POTION);
        heal.apply(zombiePot);
        zombiePotmeta = (PotionMeta) zombiePot.getItemMeta();
        zombiePotmeta.setDisplayName("§bZombie Potion of Heal §7(10 §c❤§7)");
        zombiePot.setItemMeta(zombiePotmeta);
        p.getInventory().setItem(1, zombiePot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bZombie Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bZombie §aclass has been taken!");
		p.updateInventory();
	}
	
	@SuppressWarnings("deprecation")
	public static void Spider(Player p) {
		p.getInventory().clear();
		setKit(p, "Spider");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		p.getInventory().setHelmet(new ItemStack(Material.IRON_HELMET));
		ItemStack SpiderBoots = new ItemStack(Material.DIAMOND_BOOTS);
		SpiderBoots.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta SpiderBootsMeta = SpiderBoots.getItemMeta();
		SpiderBootsMeta.setDisplayName("§b Spider Boots");
		SpiderBoots.setItemMeta(SpiderBootsMeta);
		p.getInventory().setBoots(SpiderBoots);
		p.getActivePotionEffects().clear();
		ItemStack SpiderSword = new ItemStack(Material.DIAMOND_SWORD);
		SpiderSword.addUnsafeEnchantment(Enchantment.DURABILITY, 2);
		ItemMeta SpiderSwordMeta = SpiderSword.getItemMeta();
		SpiderSwordMeta.setDisplayName("§bSpider Sword");
		SpiderSword.setItemMeta(SpiderSwordMeta);
		p.getInventory().setItem(0, SpiderSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		spiderPot = new ItemStack(Material.POTION, 2);
        heal.apply(spiderPot);
        spiderPotmeta = (PotionMeta) spiderPot.getItemMeta();
        spiderPotmeta.setDisplayName("§bSpider Potion of Heal §7(8 §c❤§7)");
        spiderPot.setItemMeta(spiderPotmeta);
        p.getInventory().setItem(1, spiderPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bSpider Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bSpider §aclass has been taken!");
		p.giveExpLevels(100);
		p.updateInventory();
	}
	
	@SuppressWarnings("deprecation")
	public static void Dreadlord(Player p) {
		p.getInventory().clear();
		setKit(p, "Dreadlord");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		ItemStack DreadlordHelmet = new ItemStack(Material.DIAMOND_HELMET);
		DreadlordHelmet.addUnsafeEnchantment(Enchantment.PROTECTION_FIRE, 1);
		DreadlordHelmet.addUnsafeEnchantment(Enchantment.PROTECTION_EXPLOSIONS, 2);
		ItemMeta DreadlordHelmetMeta = DreadlordHelmet.getItemMeta();
		DreadlordHelmetMeta.setDisplayName("§b Dreadlord Helmet");
		DreadlordHelmet.setItemMeta(DreadlordHelmetMeta);
		p.getInventory().setHelmet(DreadlordHelmet);
		p.getActivePotionEffects().clear();
		ItemStack DreadlordSword = new ItemStack(Material.DIAMOND_SWORD);
		DreadlordSword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		DreadlordSword.addUnsafeEnchantment(Enchantment.DAMAGE_UNDEAD, 1);
		ItemMeta DreadlordSwordMeta = DreadlordSword.getItemMeta();
		DreadlordSwordMeta.setDisplayName("§bDreadlord Sword");
		DreadlordSword.setItemMeta(DreadlordSwordMeta);
		p.getInventory().setItem(0, DreadlordSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		dreadPot = new ItemStack(Material.POTION, 2);
        heal.apply(dreadPot);
        dreadPotmeta = (PotionMeta) dreadPot.getItemMeta();
        dreadPotmeta.setDisplayName("§bDreadlord Potion of Heal §7(8 §c❤§7)");
        dreadPot.setItemMeta(dreadPotmeta);
        p.getInventory().setItem(1, dreadPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bDreadlord Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bDreadlord §aclass has been taken!");
		p.updateInventory();
	}
	@SuppressWarnings("deprecation")
	public static void Enderman(Player p) {
		p.getInventory().clear();
		setKit(p, "Enderman");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		p.getInventory().setHelmet(new ItemStack(Material.IRON_HELMET));
		ItemStack EndyBoots = new ItemStack(Material.DIAMOND_BOOTS);
		EndyBoots.addUnsafeEnchantment(Enchantment.PROTECTION_FALL, 4);
		ItemMeta EndyBootsMeta = EndyBoots.getItemMeta();
		EndyBootsMeta.setDisplayName("§b Enderman Boots");
		EndyBoots.setItemMeta(EndyBootsMeta);
		p.getInventory().setBoots(EndyBoots);
		p.getActivePotionEffects().clear();
		ItemStack EndySword = new ItemStack(Material.IRON_SWORD);
		EndySword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta EndySwordMeta = EndySword.getItemMeta();
		EndySwordMeta.setDisplayName("§bEnderman Sword");
		EndySword.setItemMeta(EndySwordMeta);
		p.getInventory().setItem(0, EndySword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		endyPot = new ItemStack(Material.POTION, 2);
        heal.apply(endyPot);
        endyPotmeta = (PotionMeta) endyPot.getItemMeta();
        endyPotmeta.setDisplayName("§bEnderman Potion of Heal §7(8 §c❤§7)");
        endyPot.setItemMeta(endyPotmeta);
        p.getInventory().setItem(1, endyPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bEnderman Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bEnderman §aclass has been taken!");
		p.updateInventory();
	}	
	@SuppressWarnings("deprecation")
	public static void Herobrine(Player p) {
		p.getInventory().clear();
		setKit(p, "Herobrine");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		ItemStack DreadlordHelmet = new ItemStack(Material.IRON_HELMET);
		DreadlordHelmet.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
		ItemMeta DreadlordHelmetMeta = DreadlordHelmet.getItemMeta();
		DreadlordHelmetMeta.setDisplayName("§b Herobrine Helmet");
		DreadlordHelmet.setItemMeta(DreadlordHelmetMeta);
		p.getInventory().setHelmet(DreadlordHelmet);
		p.getActivePotionEffects().clear();
		ItemStack DreadlordSword = new ItemStack(Material.DIAMOND_SWORD);
		DreadlordSword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta DreadlordSwordMeta = DreadlordSword.getItemMeta();
		DreadlordSwordMeta.setDisplayName("§bHerobrine Sword");
		DreadlordSword.setItemMeta(DreadlordSwordMeta);
		p.getInventory().setItem(0, DreadlordSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		hbPot = new ItemStack(Material.POTION, 2);
        heal.apply(hbPot);
        hbPotmeta = (PotionMeta) hbPot.getItemMeta();
        hbPotmeta.setDisplayName("§bHerobrine Potion of Heal §7(6 §c❤§7)");
        hbPot.setItemMeta(hbPotmeta);
        p.getInventory().setItem(1, hbPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bHerobrine Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bHerobrine §aclass has been taken!");
		p.updateInventory();
	}
	@SuppressWarnings("deprecation")
	public static void Skeleton(Player p) {
		p.getInventory().clear();
		setKit(p, "Skeleton");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		ItemStack DreadlordHelmet = new ItemStack(Material.DIAMOND_HELMET);
		DreadlordHelmet.addUnsafeEnchantment(Enchantment.PROTECTION_PROJECTILE, 4);
		ItemMeta DreadlordHelmetMeta = DreadlordHelmet.getItemMeta();
		DreadlordHelmetMeta.setDisplayName("§b Skeleton Helmet");
		DreadlordHelmet.setItemMeta(DreadlordHelmetMeta);
		p.getInventory().setHelmet(DreadlordHelmet);
		p.getActivePotionEffects().clear();
		ItemStack DreadlordSword = new ItemStack(Material.IRON_AXE);
		DreadlordSword.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
		DreadlordSword.addUnsafeEnchantment(Enchantment.DIG_SPEED, 1);
		ItemMeta DreadlordSwordMeta = DreadlordSword.getItemMeta();
		DreadlordSwordMeta.setDisplayName("§bSkeleton Axe");
		DreadlordSword.setItemMeta(DreadlordSwordMeta);
		p.getInventory().setItem(0, DreadlordSword);
		ItemStack DreadlordBow = new ItemStack(Material.BOW);
		DreadlordBow.addUnsafeEnchantment(Enchantment.DURABILITY, 2);
		DreadlordBow.addUnsafeEnchantment(Enchantment.ARROW_DAMAGE, 4);
		ItemMeta DreadlordBowMeta = DreadlordBow.getItemMeta();
		DreadlordBowMeta.setDisplayName("§bSkeleton Bow");
		DreadlordBow.setItemMeta(DreadlordBowMeta);
		p.getInventory().setItem(1, DreadlordBow);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		skelyPot = new ItemStack(Material.POTION, 2);
        heal.apply(skelyPot);
        skelyPotmeta = (PotionMeta) skelyPot.getItemMeta();
        skelyPotmeta.setDisplayName("§bSkeleton Potion of Heal §7(8 §c❤§7)");
        skelyPot.setItemMeta(skelyPotmeta);
        p.getInventory().setItem(2, skelyPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bSkeleton Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(3, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.getInventory().addItem(new ItemStack(Material.ARROW, 64));
		p.sendMessage("§aThe §bSkeleton §aclass has been taken!");
		p.updateInventory();
	}
	@SuppressWarnings("deprecation")
	public static void Creeper(Player p) {
		p.getInventory().clear();
		setKit(p, "Creeper");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		p.getInventory().setHelmet(new ItemStack(Material.IRON_HELMET));
		ItemStack CreeperLeggs = new ItemStack(Material.DIAMOND_LEGGINGS);
		CreeperLeggs.addUnsafeEnchantment(Enchantment.PROTECTION_EXPLOSIONS, 4);
		ItemMeta CreeperLeggsMeta = CreeperLeggs.getItemMeta();
		CreeperLeggsMeta.setDisplayName("§b Creeper Leggings");
		CreeperLeggs.setItemMeta(CreeperLeggsMeta);
		p.getInventory().setLeggings(CreeperLeggs);
		p.getActivePotionEffects().clear();
		ItemStack CreeperSword = new ItemStack(Material.IRON_SWORD);
		CreeperSword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta CreeperSwordMeta = CreeperSword.getItemMeta();
		CreeperSwordMeta.setDisplayName("§bCreeper Sword");
		CreeperSword.setItemMeta(CreeperSwordMeta);
		p.getInventory().setItem(0, CreeperSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		creeperPot = new ItemStack(Material.POTION, 2);
        heal.apply(creeperPot);
        creeperPotmeta = (PotionMeta) creeperPot.getItemMeta();
        creeperPotmeta.setDisplayName("§bCreeper Potion of Heal §7(8 §c❤§7)");
        creeperPot.setItemMeta(creeperPotmeta);
        p.getInventory().setItem(1, creeperPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bCreeper Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bCreeper §aclass has been taken!");
		p.updateInventory();
	}
	@SuppressWarnings("deprecation")
	public static void Blaze(Player p) {
		p.getInventory().clear();
		setKit(p, "Blaze");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setHelmet(new ItemStack(Material.IRON_HELMET));
		p.getInventory().setChestplate(new ItemStack(Material.IRON_CHESTPLATE));
		ItemStack BlazeLegs = new ItemStack(Material.IRON_LEGGINGS);
		BlazeLegs.addUnsafeEnchantment(Enchantment.PROTECTION_FIRE, 2);
		BlazeLegs.addUnsafeEnchantment(Enchantment.PROTECTION_PROJECTILE, 1);
		BlazeLegs.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
		ItemMeta BlazeLegsMeta = BlazeLegs.getItemMeta();
		BlazeLegsMeta.setDisplayName("§b Blaze Leggings");
		BlazeLegs.setItemMeta(BlazeLegsMeta);
		p.getInventory().setLeggings(BlazeLegs);
		p.getActivePotionEffects().clear();
		ItemStack DreadlordBow = new ItemStack(Material.BOW);
		DreadlordBow.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
		DreadlordBow.addUnsafeEnchantment(Enchantment.ARROW_DAMAGE,3);
		ItemMeta DreadlordBowMeta = DreadlordBow.getItemMeta();
		DreadlordBowMeta.setDisplayName("§bBlaze Bow");
		DreadlordBow.setItemMeta(DreadlordBowMeta);
		p.getInventory().setItem(0, DreadlordBow);
		ItemStack BlazeSword = new ItemStack(Material.DIAMOND_SWORD);
		BlazeSword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta BlazeSwordMeta = BlazeSword.getItemMeta();
		BlazeSwordMeta.setDisplayName("§bBlaze Sword");
		BlazeSword.setItemMeta(BlazeSwordMeta);
		p.getInventory().setItem(1, BlazeSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		blazePot = new ItemStack(Material.POTION, 2);
        heal.apply(blazePot);
        blazePotmeta = (PotionMeta) blazePot.getItemMeta();
        blazePotmeta.setDisplayName("§bBlaze Potion of Heal §7(8 §c❤§7)");
        blazePot.setItemMeta(blazePotmeta);
        p.getInventory().setItem(2, blazePot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bBlaze Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(3, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.getInventory().addItem(new ItemStack(Material.ARROW, 64));
		p.setLevel(100);
		p.sendMessage("§aThe §bBlaze §aclass has been taken!");
		p.updateInventory();
	}
	@SuppressWarnings("deprecation")
	public static void Pigman(Player p) {
		p.getInventory().clear();
		setKit(p, "Pigman");
		p.setMaxHealth(40);
		p.setHealth(40);
		p.getInventory().setHelmet(new ItemStack(Material.AIR));
		p.getInventory().setChestplate(new ItemStack(Material.AIR));
		p.getInventory().setLeggings(new ItemStack(Material.AIR));
		p.getInventory().setBoots(new ItemStack(Material.AIR));
		p.getActivePotionEffects().clear();
		p.getInventory().setBoots(new ItemStack(Material.IRON_BOOTS));
		p.getInventory().setHelmet(new ItemStack(Material.IRON_HELMET));
		p.getInventory().setLeggings(new ItemStack(Material.IRON_LEGGINGS));
		ItemStack PigmanChest = new ItemStack(Material.DIAMOND_CHESTPLATE);
		PigmanChest.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta PigmanChestMeta = PigmanChest.getItemMeta();
		PigmanChestMeta.setDisplayName("§b Pigman Chestplate");
		PigmanChest.setItemMeta(PigmanChestMeta);
		p.getInventory().setChestplate(PigmanChest);
		p.getActivePotionEffects().clear();
		ItemStack PigmanSword = new ItemStack(Material.DIAMOND_SWORD);
		PigmanSword.addUnsafeEnchantment(Enchantment.DURABILITY, 3);
		ItemMeta PigmanSwordMeta = PigmanSword.getItemMeta();
		PigmanSwordMeta.setDisplayName("§bPigman Sword");
		PigmanSword.setItemMeta(PigmanSwordMeta);
		p.getInventory().setItem(0, PigmanSword);
		Potion heal = new Potion(PotionType.INSTANT_HEAL);
		pigPot = new ItemStack(Material.POTION);
        heal.apply(pigPot);
        pigPotmeta = (PotionMeta) pigPot.getItemMeta();
        pigPotmeta.setDisplayName("§bPigman Potion of Heal §7(10 §c❤§7)");
        pigPot.setItemMeta(pigPotmeta);
        p.getInventory().setItem(1, pigPot);
		Potion speed = new Potion(PotionType.SPEED);
        ItemStack potion1 = new ItemStack(Material.POTION, 2);
        speed.apply(potion1);
        PotionMeta meta1 = (PotionMeta) potion1.getItemMeta();
        meta1.setDisplayName("§bPigman Potion of Speed II");
        meta1.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 15 * 20, 1), false);
        potion1.setItemMeta(meta1);
        p.getInventory().setItem(2, potion1);
		p.getInventory().addItem(new ItemStack(Material.COMPASS));
		new TrackerTask (p).runTaskTimer(Main.getPlugin(), 0L, 5L);
		p.sendMessage("§aThe §bPigman §aclass has been taken!");
		p.updateInventory();
	}
}
